name: Sync Leetcode

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync
        uses: joshcai/leetcode-sync@v1.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN_FOR_LEETCODE }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: LEETCODE_PYTHON_AND_JAVASCRIPT/problems
          #verbose: true
